DATA_FOLDER_NAME = "DataFolders"

TAGS_COUNT_FILE_NAME = "Tags Count Info.txt"

BY_CHAPTER_FOLDER_NAME = "By Chapter Info"

AGE_GROUP_SECTION = "rating"
CHAPTERS_SECTION = "chapters"
COMMENTS_SECTION = "comments"
LIKES_SECTION = "kudos"
RELATIONSHIPS_SECTION = "category"
TAGS_SECTION = "tag"
STORY_COUNT_SECTION = "stories"
VIEWS_SECTION = "hits"
WARNINGS_SECTION = "warnings"
WORDS_SECTION = "words"
WORK_STATUS_SECTION = "iswip"

BY_CHAPTER_VALUE_SECTIONS = [
        COMMENTS_SECTION,
        LIKES_SECTION,
        VIEWS_SECTION,
        WORDS_SECTION
]

BY_CHAPTER_SECTIONS = [
        AGE_GROUP_SECTION, 
        RELATIONSHIPS_SECTION, 
        WARNINGS_SECTION, 
        WORK_STATUS_SECTION
]