DATA_FOLDER_NAME = "DataFolders"
PAGE_NUMBER_INDICATOR = "page="

WEBSCRAPED_DATA_FILE_NAME = "WebScrapeData.json"

GENERAL_STATS_FOLDER_NAME = "General Info"
GENERAL_STATS_FILE_NAME = "General Info.txt"
TAGS_COUNT_FILE_NAME = "Tags Count Info.txt"

BY_CHAPTER_FOLDER_NAME = "By Chapter Info"

AGE_GROUP_SECTION = "rating"
CHAPTERS_SECTION = "chapters"
COMMENTS_SECTION = "comments"
LIKES_SECTION = "kudos"
RELATIONSHIPS_SECTION = "category"
TAGS_SECTION = "tag"
STORY_COUNT_SECTION = "stories"
VIEWS_SECTION = "hits"
WARNINGS_SECTION = "warnings"
WORDS_SECTION = "words"
WORK_STATUS_SECTION = "iswip"

BY_CHAPTER_SECTIONS = [
        AGE_GROUP_SECTION, 
        RELATIONSHIPS_SECTION, 
        WARNINGS_SECTION, 
        WORK_STATUS_SECTION
]